#!/usr/bin/env python3

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")

    user = sys.argv[1]

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # get tweets and check if successful
    tweets = helpers.get_user_timeline(user, 50)
    if tweets == None:
        sys.exit("Unable to access user's tweets")

    for tweet in tweets:
        score = analyzer.analyze(tweet)
        output = " ".join([str(score), tweet])
        if score > 0.0:
            print(colored(output, "green"))
        elif score < 0.0:
            print(colored(output, "red"))
        else:
            print(colored(output, "yellow"))

if __name__ == "__main__":
    main()
